---
label: Design Settings
hide_body: true
fields:
- name: primary_color
  type: color
  label: Primary Color
  config:
    required: false
    color_format: Hex
  description: Adjust the background color of the About Page
  default: "#B1BCBC"
