---
label: Site Config
hide_body: true
fields:
- type: text
  name: baseURL
  label: baseURL
- type: text
  name: languageCode
  label: languageCode
- type: text
  name: title
  label: title
- type: text
  name: theme
  label: theme
